# Paths
credentials_path: ./credentials/credentials.json
data_path: ./data
model_path: ./model

# Users
users:
  paulo: cylbn90p5n1gstle3q83bksox
  amelia: ameliacss

# Model configuration
model:
  layers:
    hidden_1:
      units: 5
      activation: relu
  #    hidden_2:
  #      units: 5
  #      activation: relu
  epochs: 100
  batch_size: 128
  learning_rate: 0.05

# Features configuration
features:
  target: LABEL
  categorical_features: [key, mode, time_signature]
  categorical_labels:
    key: [-1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
    mode: [0, 1]
    time_signature: [1, 3, 4, 5]
  numerical_features:
    [
      popularity,
      danceability,
      energy,
      loudness,
      speechiness,
      acousticness,
      instrumentalness,
      liveness,
      valence,
      tempo,
      duration_ms,
      timbre_0,
      timbre_1,
      timbre_2,
      timbre_3,
      timbre_4,
      timbre_5,
      timbre_6,
      timbre_7,
      timbre_8,
      timbre_9,
      timbre_10,
      timbre_11,
      pitches_0,
      pitches_1,
      pitches_2,
      pitches_3,
      pitches_4,
      pitches_5,
      pitches_6,
      pitches_7,
      pitches_8,
      pitches_9,
      pitches_10,
      pitches_11,
    ]
  one_hot_encode_categorical: True
  normalize_numerical: True
